language: ruby
cache: bundler

before_install:
  - rvm @global do gem uninstall bundler --all --executables
  - gem uninstall bundler --all --executables
  - gem install bundler --version '1.15.4'

sudo: false
